### ISSUE TITLE
Create a db.js file

### ISSUE THREAD

**Issue by bwobbones** [bwobbones/resource#58]
As per http://howtonode.org/node-js-and-mongodb-getting-started-with-mongojs

Seems like a good practice.

**Comment by kahgoh** [comment]
@bwobbones Please clarify what does the db.js file do? (Did you provide the right link?)

**Comment by bwobbones** [comment]
Ha!  That link was from the JIRA import, I think I saw it and was inspired to separate the database connection into it's own file.  You have already done this and I'm adding to it now.  I'll assign back to me and then close.

**Comment by kahgoh** [comment]
Great!! Its already done then!

**Comment by bwobbones** [comment]
Yep!
