### ISSUE TITLE
Stop sending passwords in clear text

### ISSUE THREAD

**Issue by bwobbones** [bwobbones/resource#67]
Should be able to port the code from Gunslinger for this one.

**Comment by kahgoh** [comment]
Gunslinger only stores passwords for local authentication in encrypted form. I don't think it encrypts it and sends it (I think we just have to configure the server to use an SSL connection for that).

**Comment by kahgoh** [comment]
The code from Gunslinger was ported and merged into default branch in commit 18fd431.

**Comment by bwobbones** [comment]
Hmm, yes: http://stackoverflow.com/questions/2003262/how-to-send-password-securely-via-http-using-javascript-in-absence-of-https

SSL is covered by bwobbones/resource#69 so I guess this one should be closed?

**Comment by kahgoh** [comment]
Yeah, I agree this one should be closed as #69 will achieve this as well.
